apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jmfo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-jmfo@sha256:085cac6f92e31d0f815da43fd06a0a35bca467e85361bae09f15c265f35ad609
        name: my-nodejs
        resources: {}
status: {}
